version: '3.7'

volumes:
    logs:
        driver: local

services:
    build:
        image: php:7-alpine
        working_dir: /var/www
        command: ./composer.phar install --no-plugins --no-scripts
        volumes:
            - .:/var/www
    api:
        build: .
        depends_on:
            - build
        command: php -S 0.0.0.0:8080 -t public
        ports:
            - 80:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
